// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

var api_key = "";
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: api_key,
    appId: '1:995451039078:web:766e565ad7e025b7cf6ca7',
    messagingSenderId: '995451039078',
    projectId: 'test-exe-54f88',
    authDomain: 'test-exe-54f88.firebaseapp.com',
    storageBucket: 'test-exe-54f88.firebasestorage.app',
    measurementId: 'G-ST5C4WYJNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe7Cr3lSk7g2uDjcz6lN6bQCreiLSbba8',
    appId: '1:995451039078:android:1a946693fa07330ecf6ca7',
    messagingSenderId: '995451039078',
    projectId: 'test-exe-54f88',
    storageBucket: 'test-exe-54f88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChRYe44ZzFiUGMpaActwlLBde1hBp2oLI',
    appId: '1:995451039078:ios:0b709ed0b3da599ecf6ca7',
    messagingSenderId: '995451039078',
    projectId: 'test-exe-54f88',
    storageBucket: 'test-exe-54f88.firebasestorage.app',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChRYe44ZzFiUGMpaActwlLBde1hBp2oLI',
    appId: '1:995451039078:ios:0b709ed0b3da599ecf6ca7',
    messagingSenderId: '995451039078',
    projectId: 'test-exe-54f88',
    storageBucket: 'test-exe-54f88.firebasestorage.app',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh-gSCmFv3N61kanmqHiiO62BuVhaNElY',
    appId: '1:995451039078:web:3de10a030b055ea1cf6ca7',
    messagingSenderId: '995451039078',
    projectId: 'test-exe-54f88',
    authDomain: 'test-exe-54f88.firebaseapp.com',
    storageBucket: 'test-exe-54f88.firebasestorage.app',
    measurementId: 'G-LDRZCGGE2D',
  );
}
